name: Send winners to S3 bucket and email winners

on:
  schedule:
    - cron: "0 20 * * *"

env:
  GITHUB_TOKEN: ${{ secrets.TOKEN }}
  AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
  AWS_REGION: ${{ secrets.AWS_REGION }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:
  run:
    name: Send winners to s3 bucket and email the winners
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16.x"
      - name: Keep npm cache around to speed up installs
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.OS }}-build-${{ hashFiles('**/package-lock.json') }}
      - name: Install dependencies
        run: npm ci --no-audit
      
      - name: Get S3 data and put it into archive folder
        run: aws s3 sync s3://strava-archive ./archive

      - name: Send winners to s3 and send email
        run: npx tsx sendWinners.ts
